@rootApi = http://localhost:8000/api/v1/task

@userApi = {{rootApi}}/user

### server testing get
GET {{rootApi}}

### POST method
POST {{rootApi}}
Content-Type: application/json

{
    "name": "Hari",
    "address": "Perth",
    "phone": "040500399434",
    "spouse": "Sudha",
    "bike": "Harley"
    
}

### put method
PATCH  {{rootApi}}
Content-Type: application/json

{
    "_id":"64afd3116225731d10cc8357",
    "bike": "Roma"
}

### delete method
DELETE {{rootApi}}/64afd854d54cd0f3599cd292
